name: CD

on:
  push:
    tags:
      - 'v*' # 当你推送 v1.0.2 这样的标签时触发

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@v3
    permissions:
      contents: write
    with:
      pnpm-version: 9
      node-version: 22
      java-version: 21
      # 确保这里为 false 或者删除，以便它能处理 Release 附件
      skip-appstore-release: true
